### ISSUE TITLE
After reconnection, Extrusion/Temp options are gone

### ISSUE THREAD

**Issue by sam0737** [qtquickvcp/Machineface#2]
Version: machinekit-client_v0.9-13_windows_x86.zip
Repro Step:
1. Start machinekit, run Machineface, connects
2. Stop machinekit (Ctrl-C), Machineface will detect disconnection, and kept retrying
3. Start machinekit
4. Machineface reconnects.
Problem - after reconnect, the extrusion axis and temperature controls are gone.

Note 1: velocity extrusion configuration. Using rcomp defined as fdm-e0, fdm-hbp, fdm-ve-jog, fdm-ve-params, fdm-e0-pid.
Note 2: Starting a new machineface will have everything fine.

**Comment by machinekoder** [comment]
Thanks, that is most likely due to the HalRemoteComponents connecting too early in the HAL configuration process. I think I have a clue how to solve this problem.

**Comment by machinekoder** [comment]
@sam0737 Can you try to move `loadusr haltalk` in your HAL file to the end of the file. This way the HAL service is announced after the HAL configuration is set up. So the remote components should be able to connect without any error.

**Comment by sam0737** [comment]
That does resolve the issue.

**Comment by sam0737** [comment]
I guess it should be mentioned in the docs, later?   Do you want to keep the issue around?

**Comment by machinekoder** [comment]
Not sure where to add this information.

**Comment by machinekoder** [comment]
I have added it to the QtQuickVcp README.
