### ISSUE TITLE
Machineface lacking widgets (temperatures)

### ISSUE THREAD

**Issue by icecube45** [qtquickvcp/Machineface#3]
I'm unable to see any temperature controls on the right hand side of machinekit, via console I can see the error of 

```
qml: request 256 from 'fdm-e0-{13d32a13-65d2-4ad5-a3cc-3bc987d33887}': Component not created since no_create flag set
```

Among many other errors of the same nature, each one corresponding to an extruder, heated bed, light or fan (from what I can tell).

Any help would be appreciated. 

I know that my temperatures get a valid reading, and work in axis.

Please let me know if you need more info.

**Comment by machinekoder** [comment]
Machineface uses the machinekit fdm remote components described here: https://github.com/strahlex/Machinekit-FDM-Standard
