### ISSUE TITLE
DeltaPrinter Joint/World Mode

### ISSUE THREAD

**Issue by mgiaco** [qtquickvcp/Machineface#4]
Hello,
Is there any easy way to add the possibility to switch between world and joint mode? 

thanks

**Comment by machinekoder** [comment]
Yes, there is. How is the teleop mode usually used?

**Comment by mgiaco** [comment]
Hello Allex,

I am quite new to the 3D printing, delta printer and machinekit stuff.... 
But before I used your great tools around machinekit I used the old Axis UI and there I can switch from world to joint mode and vice versa. For a Kossel if you have homed the machine it is not meaningful to jog in joint mode anymore. Or if you like to touch off the z axis you must be in world mode because otherwise it is not possible to move correctly to the zero position with joging. And then it is not possible to touch off the z axis the way you want. So it would be great if there is any button to switch the mode. 

Do you see any possibility to add this - that would be really awesome. 

Is there any documentation how machineface - machinekit client with qtuickvcp works in the background I found no code in machineface I also found no code in the machinekit client. So I understand that in the background zeromq and protobuffers are used. But how does this work with remote UIs. Can you give me a hint where to start I want to understand it more. I think that technology is quite awesome. Maybe I can use this for some other project I want to realize. The best idea would be to start with plain qtquick - right.

thx

**Comment by mgiaco** [comment]
Hello Alex,

So I did not find any solution for this problem. Can you help me here I do not know where to start.

I tried the recommendations from the machinekit group:

halcmd setp halui.mode.teleop 1

But it seems not to work. So after I tried this I cannot move/jog and after some time machineface was hangs and I need to restart the BBB.

Thx mathias

**Comment by machinekoder** [comment]
Is there a simulator config with this type of setup?

**Comment by mgiaco** [comment]
What do you exactly mean with simulator config?

This is my setting: https://github.com/mgiaco/MiniKossel-CRAMPS

**Comment by machinekoder** [comment]
Just added a check box to the settings tab, hope that helps for a start

**Comment by machinekoder** [comment]
@mgiaco Parts of the Machinetalk documentation are in the Machinekit docs. Furthermore, I have some papers on this topic which I probably should upload somewhere. Send me a PN so I can send them to you.

**Comment by mgiaco** [comment]
Many thanks
