### ISSUE TITLE
Keyboard bindings active in MDI tab

### ISSUE THREAD

**Issue by darenschwenke** [qtquickvcp/Machineface#7]
Having the keyboard shortcut bindings active while in the MDI tab result in annoying and un-intended movement.
Specifically, the arrow keys should scroll through the command history while in MDI instead of causing movement.

**Comment by machinekoder** [comment]
Good point. The keyboard bindings are assigned here: https://github.com/machinekoder/Machineface/blob/master/Machineface/JogKeyHandler.qml

**Comment by machinekoder** [comment]
@darenschwenke Can you please try https://github.com/machinekoder/Machineface/pull/8

**Comment by darenschwenke** [comment]
Yeah.  I just removed them all in my local copy as more often than not,
they just caused problems.
Just thought I should finally start documenting things.
Thank you.

**Comment by darenschwenke** [comment]
My target has been reduced to a pile of parts while I was trying to get a
BBGW working.  It will be a few days before I can test.
